---
  name: Lint Code Base
  
  on: [push, pull_request]
  
  permissions:
    contents: read      
    statuses: write     
  
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup JDK
          uses: actions/setup-java@v2
          with:
            java-version: '21'           
            distribution: 'adopt'        
  
        - name: Run Super Linter
          uses: github/super-linter@v3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  